"""Recriação do banco de dados

Revision ID: 50a61dfe545e
Revises: 
Create Date: 2025-03-26 02:47:15.670688

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '50a61dfe545e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('TypeHall',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('password', sa.String(length=100), nullable=False),
    sa.Column('address', sa.String(length=100), nullable=False),
    sa.Column('typeUser', sa.Enum('OWNER', 'CONTRACTOR', 'BOTH', name='typeuserenum'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('Halls',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('location', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('fk_owner', sa.Integer(), nullable=False),
    sa.Column('fk_typeHall', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['fk_owner'], ['Users.id'], ),
    sa.ForeignKeyConstraint(['fk_typeHall'], ['TypeHall.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Halls')
    op.drop_table('Users')
    op.drop_table('TypeHall')
    # ### end Alembic commands ###
